// All streams
export const REQ_STREAMS = 'REQ_STREAMS';
export const RECEIVE_STREAMS = 'RECEIVE_STREAMS';
// Single stream
export const REQ_ONE_STREAM = 'REQ_ONE_STREAM';
export const RECEIVE_STREAM = 'RECEIVE_STREAM';
// Channel videos
export const RECEIVE_VIDEOS_FROM_CHANNEL = 'RECEIVE_VIDEOS_FROM_CHANNEL';
// Games
export const RECEIVE_ONE_GAME = 'RECEIVE_ONE_Game';
export const RECEIVE_ALL_GAMES = 'RECEIVE_ALL_GAMES';
// Features
export const RECEIVE_FEATURES_STREAMS = 'RECEIVE_FEATURES_STREAMS';

export const ADD_GAME_TO_FAVORITE = 'ADD_GAME_TO_FAVORITE';
export const REMOVE_GAME_FROM_FAVORITE = 'REMOVE_GAME_FROM_FAVORITE';
